version: '3'

services:
  server:
    image: klakegg/hugo:0.101.0-ext-alpine
    container_name: hugo
    command: server
    entrypoint: hugo
    volumes:
      - "./hugo:/src"
    ports:
      - "1313:1313"
    networks:
        - mylocal
  app:
    build: ./proxy
    container_name: proxy
    volumes:
      - "./hugo/content:/app/static"
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DADATA_API_KEY=${DADATA_API_KEY}
      - DADATA_SECRET_KEY=${DADATA_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
    networks:
        - mylocal
networks:
    mylocal:
        driver: bridge